import { StyleSheet } from 'react-native';

export const createStyles = (colors: any) => StyleSheet.create({
  homeSection: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    backgroundColor: colors.background, 
  },
  homeContent: {
    flex: 1,
    width: '100%',
    maxWidth: 500,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 100,
    backgroundColor: colors.background === '#1C1C1E' ? 'rgba(0,0,0,0.3)' : 'rgba(255,255,255,0.1)',
  },
  profileContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileImage: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 2,
    borderColor: colors.cardBackground,
    marginBottom: 20,
    elevation: 10,
    shadowColor: colors.shadow, 
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
  },
  themeToggle: {
    position: 'absolute',
    top: -20, 
    right: -20, 
    backgroundColor: colors.cardBackground === '#FFFFFF' ? 'rgba(255, 255, 255, 0.7)' : 'rgba(44, 44, 46, 0.7)',
    padding: 8,
    borderRadius: 20,
    elevation: 5,
    shadowColor: colors.shadow, 
    shadowOpacity: 0.25,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  name: {
    fontSize: 42,
    fontWeight: '700',
    color: colors.text, 
    marginBottom: 20,
    textAlign: 'center',
  },
  title: {
    fontSize: 18,
    color: colors.secondaryText || colors.text, 
    fontWeight: '400',
    textAlign: 'center',
    lineHeight: 25,
    marginBottom: 15,
    paddingHorizontal: 10,
  },
  socialIcons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 15,
    marginVertical: 10,
  },
  iconButton: {
    padding: 8,
    borderRadius: 25,
    backgroundColor: 'transparent',
  },
  hireButton: {
    backgroundColor: colors.DUSTY_PURPLE, 
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 50,
    marginVertical: 30,
    elevation: 8,
    shadowColor: colors.shadow, 
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
  },
  hireButtonText: {
    color: colors.textButton, 
    fontSize: 16,
    fontWeight: '600',
  },
});